"""empty message

Revision ID: 30e854bdc8bd
Revises: None
Create Date: 2016-05-25 15:54:24.874201

"""

# revision identifiers, used by Alembic.
revision = '30e854bdc8bd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=1024), nullable=True),
    sa.Column('password', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keloud_username', sa.String(length=1024), nullable=True),
    sa.Column('gcm_token', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gcm_token')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    op.drop_table('auth')
    ### end Alembic commands ###
